# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 16:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registerdesk',
            old_name='cand_college',
            new_name='candidate_college',
        ),
        migrations.RenameField(
            model_name='registerdesk',
            old_name='cand_dept',
            new_name='candidate_department',
        ),
        migrations.RenameField(
            model_name='registerdesk',
            old_name='cand_name',
            new_name='candidate_name',
        ),
        migrations.RenameField(
            model_name='registerdesk',
            old_name='event_part',
            new_name='event_participating',
        ),
    ]
