# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 16:12
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0002_auto_20170217_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registerdesk',
            name='event_participating',
        ),
        migrations.AddField(
            model_name='registerdesk',
            name='events_enrolling',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Sciece Quiz'), ('2', 'Science Model'), ('3', 'Paper Presentation'), ('4', 'Spell bee'), ('5', 'connections'), ('6', 'Poster Painting'), ('7', 'Short Film')], default=1, max_length=13),
            preserve_default=False,
        ),
    ]
