# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0004_auto_20170218_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerdesk',
            name='events_enrolled',
            field=models.ManyToManyField(to='Registration.EventList'),
        ),
    ]
