# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 12:21
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0005_registerdesk_events_enrolled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerdesk',
            name='events_enrolling',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Science Quiz', 'Science Quiz'), ('Science Model', 'Science Model'), ('Paper Presentation', 'Paper Presentation'), ('Spell bee', 'Spell bee'), ('connections', 'connections'), ('Poster Painting', 'Poster Painting'), ('Short Film', 'Short Film')], max_length=94),
        ),
    ]
