# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 12:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0007_auto_20170219_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registerdesk',
            name='events_enrolled',
        ),
        migrations.AddField(
            model_name='registerdesk',
            name='events_enrolled',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Registration.EventList'),
            preserve_default=False,
        ),
    ]
