# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0009_remove_registerdesk_events_enrolled'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlist',
            name='event_isStarted',
            field=models.BooleanField(default=False),
        ),
    ]
