# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0013_auto_20170220_2052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registerdesk',
            old_name='candidate_department',
            new_name='candidate_email',
        ),
        migrations.RemoveField(
            model_name='eventlist',
            name='event_slug',
        ),
        migrations.AddField(
            model_name='registerdesk',
            name='candidate_contact',
            field=models.CharField(default=91, max_length=12),
            preserve_default=False,
        ),
    ]
