# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0014_auto_20170221_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerdesk',
            name='candidate_contact',
            field=models.CharField(max_length=12),
        ),
    ]
