# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 13:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0015_auto_20170221_1910'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registerdesk',
            old_name='candidate_contact',
            new_name='candidate_contact_no',
        ),
    ]
