# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 15:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0017_eventwinner'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperPresentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='eventwinner',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registration.EventList'),
        ),
    ]
