# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0018_auto_20170221_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventwinner',
            name='user',
        ),
        migrations.AddField(
            model_name='eventwinner',
            name='user',
            field=models.ManyToManyField(to='Registration.EventList'),
        ),
    ]
