# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 16:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0021_auto_20170221_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventwinner',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventwinner',
            name='user',
        ),
        migrations.DeleteModel(
            name='EventWinner',
        ),
    ]
