# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0022_auto_20170221_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlist',
            name='event_time',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
