# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 10:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0024_siteconfig'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteConfig',
        ),
    ]
